name: Publish GitHub Repositories HTML

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate HTML page and README
        run: python main.py

      - name: Deploy to GitHub Pages and update README
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *
          git commit -m "Publish GitHub Repositories HTML and update README"
          git push
